{
 "title": "My_dash",
 "time": { "from": "2024-08-24T14:37:10.462Z", "to": "2024-08-24T16:37:10.462Z" },
 "panels": [
  {
   "title": "Security requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_total",
     "legendFormat": "{{job}}, {{status}}, {{method}}"
    }
   ]
  },
  {
   "title": "Upload requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total",
     "legendFormat": "{{job}}, {{status}}, {{method}}"
    }
   ]
  },
  {
   "title": "Minio files",
   "type": "stat",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_usage_object_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}